SELECT * from ORDERS;
SELECT SUM(PURCHASE_AMOUNT) from ORDERS;
SELECT MAX(PURCHASE_AMOUNT) from ORDERS;
SELECT MIN(PURCHASE_AMOUNT) from ORDERS;
SELECT AVG(PURCHASE_AMOUNT) from ORDERS;
SELECT COUNT(CUSTOMER_ID) from ORDERS; 

